# Number of profiles to generate
NUM_PROFILES = 10000
TOLERANCE = 1

# Profile's percentage for two options (Yes or No)
ALCOHOLIC_PERCENTAGE = 18
ANEMIMA_PERCENTAGE = 28
ANTIDEPRESSANTS_PERCENTAGE = 20.4
ASCVD_PERCENTAGE = 4.5
COVID_HISTORY_PERCENTAGE = 6.3
DYSLIPIDEMIA_PERCENTAGE = 58
FAMILIAL_HYPERCHOLESTEROLEMIA = 0.5
FATTY_LIVER_PERCENTAGE = 25
MELLITUS_DIABETIS_PERCENTAGE = 11
MENS_PERCENTAGE = 48.98
PSYCHOSIS_PERCENTAGE = 1.2
RHEUMATOID_PERCENTAGE = 1.07
SMOKER_PERCENTAGE = 21
SYSTEMIC_ERYTHEMATOSUS_PERCENTAGE = 0.09

# Ethnic's percentage
AFRICAN_ETHNIC_PERCENTAGE = 2.7
ASIAN_ETHNIC_PERCENTAGE = 0.6
CAUCASIAN_ETHNIC_PERCENTAGE = 96.7

# Gender dependant percentage
ERECTILE_DYSFUNCTION = 12.1
MEN_ANTIDIABETIC_TREATMENT_PERCENTAGE = 66
MEN_ANTIHYPERTENSIVE_TREATMENT_PERCENTAGE = 68
MEN_ANXIETY_DISORDER_PERCENTAGE = 4.5
MEN_CHRONIC_OBSTRUCTIVE_PERCENTAGE = 14.3
MEN_CHRONIC_RENAL_FAILURE_PERCENTAGE = 14.4
MEN_DEPRESSIVE_DISORDER_PERCENTAGE = 2.3
MEN_HYPERTENSION_PERCENTAGE = 36
MEN_LIPID_LOWERING_TREATMENT_PERCENTAGE = 39
MEN_MIGRAINES_PERCENTAGE = 6
MEN_POVERTY_PERCENTAGE = 22.2
MEN_SEVERE_OBSTRUCTIVE_SLEEP_APNEA_PERCENTAGE = 6.8
WOMEN_ANTIDIABETIC_TREATMENT_PERCENTAGE = 69
WOMEN_ANTIHYPERTENSIVE_TREATMENT_PERCENTAGE = 73
WOMEN_ANXIETY_DISORDER_PERCENTAGE = 8.8
WOMEN_CHRONIC_OBSTRUCTIVE_PERCENTAGE = 3.9
WOMEN_CHRONIC_RENAL_FAILURE_PERCENTAGE = 12.9
WOMEN_DEPRESSIVE_DISORDER_PERCENTAGE = 5.9
WOMEN_HYPERTENSION_PERCENTAGE = 53
WOMEN_LIPID_LOWERING_TREATMENT_PERCENTAGE = 42
WOMEN_MIGRAINES_PERCENTAGE = 16.7
WOMEN_POVERTY_PERCENTAGE = 21
WOMEN_SEVERE_OBSTRUCTIVE_SLEEP_APNEA_PERCENTAGE = 1.9

# Age dependant percentage
ATRIAL_FIBRILLATION_AGE_DEPENDANT_PERCENTAGE = 4.4
ATRIAL_FIBRILLATION_PERCENTAGE = 0.7
HIGH_ALZHEIMER_PERCENTAGE = 10
LOW_ALZHEIMER_PERCENTAGE = 5

# Renal dependant percentage
KIDNEY_TRANSPLANT_PERCENTAGE = 0.01
RENAL_REPLACEMENT_THERAPY = 0.13

# ICM Gaussian variables
ICM_MEAN = 26.8
ICM_SKEW = 0.1095
ICM_STANDARD_DEVIATION = 5

# Cholesterol variables
COLT_LIMIT_VALUE = 200
COLT_MAX_VALUE = 250
COLT_MIN_VALUE = 150
COLT_PERCENTAGE = 50.5
LDL_LIMIT_VALUE = 130
LDL_MAX_VALUE = 180
LDL_MIN_VALUE = 80
LDL_PERCENTAGE = 44.9
MEN_TG_PERCENTAGE = 23.2
TG_MIN_VALUE = 100
TG_MAX_VALUE = 200
TG_LIMIT_VALUE = 150
WOMEN_TG_PERCENTAGE = 11.7

# Diastolic blood pressure variables
DIASTOLIC_BLOOD_PRESSURE_LIMIT_VALUE = 100
DIASTOLIC_BLOOD_PRESSURE_MAX_VALUE = 150
DIASTOLIC_BLOOD_PRESSURE_MIN_VALUE = 40
MEN_DIASTOLIC_BLOOD_PRESSURE_PERCENTAGE = 0
WOMEN_DIASTOLIC_BLOOD_PRESSURE_PERCENTAGE = 0

# Systolic blood pressure variables
MEN_SYSTOLIC_BLOOD_PRESSURE_PERCENTAGE = 49.9
SYSTOLIC_BLOOD_PRESSURE_LIMIT_VALUE = 140
SYSTOLIC_BLOOD_PRESSURE_MAX_VALUE = 200
SYSTOLIC_BLOOD_PRESSURE_MIN_VALUE = 60
WOMEN_SYSTOLIC_BLOOD_PRESSURE_PERCENTAGE = 37.1

# SCORE variables
ALPHA_CHD_MEN = -22.1
ALPHA_CHD_WOMEN = -29.8
ALPHA_NONCHD_MEN = -26.7
ALPHA_NONCHD_WOMEN = -31
CHOLESTEROL_CHD = 0.24
CHOLESTEROL_NONCHD = 0.02
P_CHD_MEN = 4.71
P_CHD_WOMEN = 6.36
P_NONCHD_MEN = 5.64
P_NONCHD_WOMEN = 6.62
SMOKER_CHD = 0.71
SMOKER_NONCHD = 0.63
SYSTOLIC_CHD = 0.018
SYSTOLIC_NONCHD = 0.022